local Diff = require("zxz.edit.inline_diff")

local function set_buf(lines)
  local b = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(b, 0, -1, false, lines)
  vim.api.nvim_set_current_buf(b)
  return b
end

describe("zxz.edit.inline_diff.compute_hunks", function()
  it("emits a single replacement hunk for a one-line change", function()
    local hunks = Diff.compute_hunks("one\ntwo\nthree\n", "one\nTWO\nthree\n", { start_line = 1, end_line = 3 })
    assert.equals(1, #hunks)
    assert.equals(2, hunks[1].old_start)
    assert.equals(1, hunks[1].old_count)
    assert.same({ "TWO" }, hunks[1].new_lines)
  end)

  it("handles a pure insertion (old_count == 0)", function()
    local hunks = Diff.compute_hunks("one\ntwo\n", "one\nbetween\ntwo\n", { start_line = 1, end_line = 2 })
    assert.equals(1, #hunks)
    assert.equals(0, hunks[1].old_count)
    assert.same({ "between" }, hunks[1].new_lines)
  end)

  it("handles a pure deletion (new_count == 0)", function()
    local hunks = Diff.compute_hunks("a\nb\nc\n", "a\nc\n", { start_line = 1, end_line = 3 })
    assert.equals(1, #hunks)
    assert.equals(1, hunks[1].old_count)
    assert.same({}, hunks[1].new_lines)
  end)

  it("offsets hunks by range.start_line", function()
    local hunks = Diff.compute_hunks("x\ny\n", "x\nY\n", { start_line = 10, end_line = 11 })
    assert.equals(11, hunks[1].old_start)
  end)
end)

describe("zxz.edit.inline_diff.render+apply", function()
  it("renders extmarks for each hunk", function()
    local b = set_buf({ "one", "two", "three" })
    Diff.render(b, { start_line = 1, end_line = 3 }, "one\nTWO\nthree")
    local marks = vim.api.nvim_buf_get_extmarks(b, vim.api.nvim_create_namespace("zxz_inline_diff"), 0, -1, {})
    assert.is_true(#marks >= 1)
    Diff.close(Diff.get(b))
  end)

  it("ga (accept_hunk via apply) lands new lines and shifts subsequent hunks", function()
    local b = set_buf({ "a", "b", "c", "d" })
    local state = Diff.render(b, { start_line = 1, end_line = 4 }, "a\nB\nc\nD")
    assert.equals(2, #state.hunks)
    -- Cursor on first hunk row.
    vim.api.nvim_win_set_cursor(0, { state.hunks[1].old_start, 0 })
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("ga", true, false, true), "x", false)
    local buf_lines = vim.api.nvim_buf_get_lines(b, 0, -1, false)
    assert.same({ "a", "B", "c", "d" }, buf_lines)
    -- After first accept, line numbers don't shift here (1-for-1), but the
    -- second hunk should still be marked pending.
    assert.equals("accepted", state.hunks[1].state)
    assert.equals("pending", state.hunks[2].state)
  end)

  it("gA accepts every hunk and closes the overlay", function()
    local b = set_buf({ "a", "b", "c" })
    local _ = Diff.render(b, { start_line = 1, end_line = 3 }, "A\nB\nC")
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("gA", true, false, true), "x", false)
    assert.same({ "A", "B", "C" }, vim.api.nvim_buf_get_lines(b, 0, -1, false))
    assert.is_nil(Diff.get(b))
  end)

  it("gR closes without applying any hunk", function()
    local b = set_buf({ "x", "y" })
    Diff.render(b, { start_line = 1, end_line = 2 }, "X\nY")
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("gR", true, false, true), "x", false)
    assert.same({ "x", "y" }, vim.api.nvim_buf_get_lines(b, 0, -1, false))
    assert.is_nil(Diff.get(b))
  end)
end)
