describe("test harness", function()
  it("loads all surviving zxz modules from runtimepath", function()
    assert.is_truthy(require("zxz"))
    assert.is_truthy(require("zxz.worktree"))
    assert.is_truthy(require("zxz.agents"))
    assert.is_truthy(require("zxz.terminal"))
    assert.is_truthy(require("zxz.context_share"))
    assert.is_truthy(require("zxz.review"))
    assert.is_truthy(require("zxz.commands"))
    assert.is_truthy(require("zxz.complete"))
    assert.is_truthy(require("zxz.core.acp_client"))
    assert.is_truthy(require("zxz.core.acp_transport"))
    assert.is_truthy(require("zxz.core.config"))
    assert.is_truthy(require("zxz.core.log"))
    assert.is_truthy(require("zxz.core.paths"))
  end)
end)
