describe("test harness", function()
  it("loads zxz modules from runtimepath", function()
    assert.is_truthy(require("zxz.core.config"))
    assert.is_truthy(require("zxz.core.history"))
    assert.is_truthy(require("zxz.core.checkpoint"))
    assert.is_truthy(require("zxz.core.reconcile"))
    assert.is_truthy(require("zxz.edit.inline_diff"))
  end)
end)
