describe("test harness", function()
  it("loads zeroxzero modules from runtimepath", function()
    assert.is_truthy(require("zeroxzero.config"))
    assert.is_truthy(require("zeroxzero.history"))
    assert.is_truthy(require("zeroxzero.checkpoint"))
    assert.is_truthy(require("zeroxzero.reconcile"))
    assert.is_truthy(require("zeroxzero.inline_diff"))
  end)
end)
